name: Build Eclipse Java distro with plugins

on:
  schedule:
    - cron: '0 17 * * 6'   # Saturdays at 17:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write  # required to create releases

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    env:
      # Update site URLs (quote to avoid YAML parsing edge-cases)
      SONAR_REPO: "https://eclipse-uc.sonarlint.org"
      SPOTBUGS_REPO: "https://spotbugs.github.io/eclipse/"
      # de.jcup editors (Albert Tregnaghi)
      BASH_REPO: "https://de-jcup.github.io/update-site-eclipse-bash-editor/update-site/"
      SQL_REPO: "https://de-jcup.github.io/update-site-eclipse-sql-editor/update-site/"
      JENKINS_REPO: "https://de-jcup.github.io/update-site-eclipse-jenkins-editor/update-site/"
      YAML_REPO: "https://de-jcup.github.io/update-site-eclipse-yaml-editor/update-site/"
      BAT_REPO: "https://de-jcup.github.io/update-site-eclipse-batch-editor/update-site/"
      HIJSON_REPO: "https://de-jcup.github.io/update-site-eclipse-hijson-editor/update-site/"
      EGRADLE_REPO: "https://de-jcup.github.io/update-site-egradle/update-site/"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get latest Eclipse SimRel train (e.g., 2025-09)
        id: train
        run: |
          set -euo pipefail
          PAGE="$(curl -fsSL https://www.eclipse.org/downloads/packages/release)"
          TRAIN="$(printf '%s' "$PAGE" | grep -Eo '[0-9]{4}-[0-9]{2} R' | head -n1 | cut -d' ' -f1)"
          if [[ -z "${TRAIN:-}" ]]; then
            echo "Could not detect latest train" >&2
            exit 1
          fi
          echo "train=$TRAIN" >> "$GITHUB_OUTPUT"

      - name: Decide if we already released this train
        id: decide
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          TRAIN="${{ steps.train.outputs.train }}"
          TAG="eclipse-java-${TRAIN}-with-plugins"
          if gh release view "$TAG" >/dev/null 2>&1; then
            echo "skip=true"  >> "$GITHUB_OUTPUT"
          else
            echo "skip=false" >> "$GITHUB_OUTPUT"
          fi
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Stop early if release already exists
        if: ${{ steps.decide.outputs.skip == 'true' }}
        run: echo "Release ${{ steps.decide.outputs.tag }} already exists. Nothing to do."

      - name: Prepare build tools
        if: ${{ steps.decide.outputs.skip == 'false' }}
        run: |
          set -euo pipefail
          sudo apt-get update -y
          sudo apt-get install -y jq unzip p7zip-full xz-utils

      - name: Download Eclipse packages (Linux & Windows)
        if: ${{ steps.decide.outputs.skip == 'false' }}
        id: dl
        run: |
          set -euo pipefail
          TRAIN="${{ steps.train.outputs.train }}"
          BASE="/technology/epp/downloads/release/${TRAIN}/R"
          LNX_FILE="eclipse-java-${TRAIN}-R-linux-gtk-x86_64.tar.gz"
          LNX_URL="https://www.eclipse.org/downloads/download.php?file=${BASE}/${LNX_FILE}"
          WIN_FILE="eclipse-java-${TRAIN}-R-win32-x86_64.zip"
          WIN_URL="https://www.eclipse.org/downloads/download.php?file=${BASE}/${WIN_FILE}"
          curl -fSL "$LNX_URL" -o "$LNX_FILE"
          curl -fSL "$WIN_URL" -o "$WIN_FILE"
          echo "linux=$LNX_FILE"   >> "$GITHUB_OUTPUT"
          echo "windows=$WIN_FILE" >> "$GITHUB_OUTPUT"

      - name: Unpack Linux Eclipse (used to install plugins headlessly)
        if: ${{ steps.decide.outputs.skip == 'false' }}
        id: unpack
        run: |
          set -euo pipefail
          tar -xzf "${{ steps.dl.outputs.linux }}"
          ECLIPSE_DIR="$(find . -maxdepth 1 -type d -name 'eclipse' | head -n1)"
          echo "eclipse_dir=$ECLIPSE_DIR" >> "$GITHUB_OUTPUT"

      - name: Resolve feature IDs from update sites
        if: ${{ steps.decide.outputs.skip == 'false' }}
        id: resolve
        run: |
          set -euo pipefail
          ECLIPSE="${{ steps.unpack.outputs.eclipse_dir }}/eclipse"

          resolve_iu() {
            local repo="$1"
            local pattern="$2"
            "$ECLIPSE" -nosplash -application org.eclipse.equinox.p2.director \
              -repository "$repo" -list \
            | awk '/feature\.group/ {print $1}' \
            | grep -Ei "$pattern" | head -n1
          }

          SONAR_IU="$(resolve_iu "${{ env.SONAR_REPO }}" 'sonar|sonarlint|sonarqube')"
          SPOT_IU="$(resolve_iu "${{ env.SPOTBUGS_REPO }}" 'spotbugs')"
          BASH_IU="$(resolve_iu "${{ env.BASH_REPO }}" 'basheditor')"
          SQL_IU="$(resolve_iu "${{ env.SQL_REPO }}" 'sqleditor')"
          JENKINS_IU="$(resolve_iu "${{ env.JENKINS_REPO }}" 'jenkins.*editor')"
          YAML_IU="$(resolve_iu "${{ env.YAML_REPO }}" 'yaml.*editor')"
          BAT_IU="$(resolve_iu "${{ env.BAT_REPO }}" 'batch.*editor|bat.*editor')"
          HIJSON_IU="$(resolve_iu "${{ env.HIJSON_REPO }}" 'hijson')"
          EGRADLE_IU="$(resolve_iu "${{ env.EGRADLE_REPO }}" 'egradle')"

          for v in SONAR_IU SPOT_IU BASH_IU SQL_IU JENKINS_IU YAML_IU BAT_IU HIJSON_IU EGRADLE_IU; do
            [[ -n "${!v}" ]] || { echo "Failed to resolve IU for $v" >&2; exit 1; }
          done

          {
            echo "SONAR_IU=$SONAR_IU"
            echo "SPOT_IU=$SPOT_IU"
            echo "BASH_IU=$BASH_IU"
            echo "SQL_IU=$SQL_IU"
            echo "JENKINS_IU=$JENKINS_IU"
            echo "YAML_IU=$YAML_IU"
            echo "BAT_IU=$BAT_IU"
            echo "HIJSON_IU=$HIJSON_IU"
            echo "EGRADLE_IU=$EGRADLE_IU"
          } >> "$GITHUB_OUTPUT"

      - name: Install plugins into Linux Eclipse using p2 director
        if: ${{ steps.decide.outputs.skip == 'false' }}
        run: |
          set -euo pipefail
          ECLIPSE="${{ steps.unpack.outputs.eclipse_dir }}/eclipse"

          REPOS=$(
            IFS=, ;
            echo "${{ env.SONAR_REPO }}","${{ env.SPOTBUGS_REPO }}","${{ env.BASH_REPO }}","${{ env.SQL_REPO }}","${{ env.JENKINS_REPO }}","${{ env.YAML_REPO }}","${{ env.BAT_REPO }}","${{ env.HIJSON_REPO }}","${{ env.EGRADLE_REPO }}"
          )
          IUS=$(
            IFS=, ;
            echo "${{ steps.resolve.outputs.SONAR_IU }}","${{ steps.resolve.outputs.SPOT_IU }}","${{ steps.resolve.outputs.BASH_IU }}","${{ steps.resolve.outputs.SQL_IU }}","${{ steps.resolve.outputs.JENKINS_IU }}","${{ steps.resolve.outputs.YAML_IU }}","${{ steps.resolve.outputs.BAT_IU }}","${{ steps.resolve.outputs.HIJSON_IU }}","${{ steps.resolve.outputs.EGRADLE_IU }}"
          )

          "$ECLIPSE" -nosplash -application org.eclipse.equinox.p2.director \
            -repository "$REPOS" \
            -installIU "$IUS" \
            -profile SDKProfile \
            -profileProperties org.eclipse.update.install.features=true \
            -destination "$(dirname "$ECLIPSE")" \
            -roaming

      - name: Create portable dropins from installed plugins
        if: ${{ steps.decide.outputs.skip == 'false' }}
        id: dropins
        run: |
          set -euo pipefail
          ECLIPSE_ROOT="${{ steps.unpack.outputs.eclipse_dir }}"
          mkdir -p dropins/custom/eclipse/plugins dropins/custom/eclipse/features
          rsync -a "${ECLIPSE_ROOT}/plugins/"  "dropins/custom/eclipse/plugins/"
          rsync -a "${ECLIPSE_ROOT}/features/" "dropins/custom/eclipse/features/"
          echo "dropins_dir=$(pwd)/dropins" >> "$GITHUB_OUTPUT"

      - name: Repack Linux distribution (with dropins)
        if: ${{ steps.decide.outputs.skip == 'false' }}
        id: packlinux
        run: |
          set -euo pipefail
          TRAIN="${{ steps.train.outputs.train }}"
          ECLIPSE_ROOT="${{ steps.unpack.outputs.eclipse_dir }}"
          cp -r "${{ steps.dropins.outputs.dropins_dir }}/custom" "${ECLIPSE_ROOT}/dropins/"
          OUT="eclipse-java-${TRAIN}-R-linux-x86_64-with-plugins.tar.gz"
          tar -czf "$OUT" -C "$(dirname "$ECLIPSE_ROOT")" "$(basename "$ECLIPSE_ROOT")"
          echo "linux_out=$OUT" >> "$GITHUB_OUTPUT"

      - name: Prepare Windows distribution (inject dropins and re-zip)
        if: ${{ steps.decide.outputs.skip == 'false' }}
        id: packwin
        run: |
          set -euo pipefail
          TRAIN="${{ steps.train.outputs.train }}"
          WIN_ZIP="${{ steps.dl.outputs.windows }}"
          mkdir win && (cd win && unzip -q "../$WIN_ZIP")
          cp -r "${{ steps.dropins.outputs.dropins_dir }}/custom" "win/eclipse/dropins/"
          OUT="eclipse-java-${TRAIN}-R-win32-x86_64-with-plugins.zip"
          (cd win && zip -qr "../$OUT" eclipse)
          echo "windows_out=$OUT" >> "$GITHUB_OUTPUT"

      - name: Generate release notes
        if: ${{ steps.decide.outputs.skip == 'false' }}
        id: notes
        run: |
          set -euo pipefail
          TRAIN="${{ steps.train.outputs.train }}"
          cat > RELEASE_NOTES.md << 'EOF'
          # Eclipse IDE for Java Developers – bundled plugins

          This release bundles the official Eclipse EPP package **with preinstalled plugins** so you don’t need Marketplace or manual update sites.

          **Included repositories / plugins**
          - SonarQube for IDE (formerly SonarLint)
          - SpotBugs Eclipse plugin
          - de.jcup editors: Bash, SQL, Jenkins, YAML, Batch (BAT), HiJSON (JSON), EGradle

          **How to use**
          - Linux: extract the `.tar.gz` and run `eclipse`.
          - Windows: unzip and run `eclipse.exe`.
          - Plugins are preinstalled via `dropins/`.

          **Notes**
          - Built automatically from the latest SimRel train.
          EOF
          echo "path=RELEASE_NOTES.md" >> "$GITHUB_OUTPUT"

      - name: Publish GitHub Release
        if: ${{ steps.decide.outputs.skip == 'false' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          gh release create "${{ steps.decide.outputs.tag }}" \
            "${{ steps.packlinux.outputs.linux_out }}" \
            "${{ steps.packwin.outputs.windows_out }}" \
            --title "Eclipse Java with plugins – ${{ steps.train.outputs.train }}" \
            --notes-file "${{ steps.notes.outputs.path }}"
